### ISSUE TITLE
Icon?

### ISSUE THREAD

**Issue by Alexey-T** [Briles/gruvbox-cudatext#1]
Hey Brian,
do you paint icons? Just wanted to ask.

**Comment by Briles** [comment]
I don't consider myself an artist or designer but I have designed icons in the past (I designed the icons for Sublime gruvbox).

**Comment by Alexey-T** [comment]
ah. I see, some designed. Cudatxt has stock ico (I got it at free set): wanted some mid-quality ico :)

**Comment by Briles** [comment]
Sorry to disappoint! I don't see anything wrong with the current CudaText icons; the stock icons are suitable.

**Comment by Alexey-T** [comment]
I like more what ppl paint for ST: 
![ee](https://cloud.githubusercontent.com/assets/4154978/14584582/d3dd94ba-045e-11e6-83de-d7a6f06ee92a.png)
