### ISSUE TITLE
The focus is not on the text

### ISSUE THREAD

**Issue by jczanfona** [Briles/gruvbox-cudatext#6]
With this line in _user.json_ the focus is not on the file at startup:
`  "ui_theme" : "gruvbox (light) (soft)",`
This other does not cause any problems:
`  "ui_theme_syntax" : "gruvbox (light) (soft)",`

Is it a known issue? How can I avoid it?

**Comment by Alexey-T** [comment]
Let’s move this topic to CudaText GitHub ?

**Comment by jczanfona** [comment]
Ok, Have I to do something?

**Comment by Alexey-T** [comment]
Yes, create issue in GitHub of CudaText , post there zip with your settings folder to reproduce this

**Comment by jczanfona** [comment]
Ok, tx
